### ISSUE TITLE
undefined result on Set-methods

### ISSUE THREAD

**Issue by Fi1osof** [shrimpy-dev/shrimpy-node#1]
For example call client.enableUser(...) OR client.setPermissions(...) returns undefined. Should {
    "success": true
}

**Comment by shrimpy-dev** [comment]
That is by design, those methods will throw if there is an error. Is there is a reason you want the success object?

**Comment by Fi1osof** [comment]
@shrimpy-dev so you should return `return await this._callEndpoint<any>(endpoint, 'POST', null, true);` instead `await this._callEndpoint<any>(endpoint, 'POST', null, true);`

`await this._callEndpoint<any>(endpoint, 'POST', null, true);` does not return anything.

**Comment by Fi1osof** [comment]
@shrimpy-dev answered [here](https://github.com/shrimpy-dev/shrimpy-node/pull/3#issuecomment-531516959).
