### ISSUE TITLE
Any plans to add websocket support?

### ISSUE THREAD

**Issue by ghost** [shrimpy-dev/shrimpy-node#2]
It'd be nice if this client also supported the shrimpy websocket, auto-reconnecting, and order book management. Are there any plans to bring this to the client?

**Comment by nnayudu** [comment]
We have added the [ShrimpyWsClient ](https://github.com/shrimpy-dev/shrimpy-node/blob/master/lib/client/shrimpy-ws-client.ts) to allow users to manage an order book based on their own requirements. At this time there are no plans to add a custom order book management class in the near future.
